#' @title write_raster_factors
#'
#' @description write_raster_factors creates a template as a csv file for
#'   supplying code definition metadata for spatial rasters if raster values are
#'   categorical.
#'
#' @details The csv template generated by write_raster_factors includes an
#'   arbitrary field name (raster_value). The number of categories can be
#'   estimated from the contents of the raster (buildFromFile = TRUE), or a
#'   range of categorical values (e.g., 1 through 15) can be provided by the
#'   user (buildFromFile = FALSE). If the user provides the range of categorical
#'   variables, the template will be constructed from the lowest to the highest
#'   number provided in increments of one but the template can be edited
#'   appropriately as constructed if this is not appropriate (e.g., remove 2
#'   from the sequence if 2 is not in fact a categorial value included in the
#'   raster). The template supports the ability to provide a definition for each
#'   level. The csv file is written with the name of the raster file +
#'   "_factors". The create_spatialRaster function will search for this file
#'   when creating a EML spatial raster entity.
#'
#' @note Constructing the template from raster content (i.e., buildFromFile =
#'   TRUE) can be extremely computationally and time intensive for large
#'   rasters.
#'
#' @param buildFromFile Logical indicating whether the raster categories should
#'   be constructed from the contents of the raster (TRUE) or if the user will
#'   provide the range of categories (FALSE, default). If TRUE, the function
#'   will identify the smallest and largest raster values, and construct a
#'   sequence from these end points.
#' @param rangeStart Starting range of categorical variables when provided by
#'   the user.
#' @param rangeEnd End range of categorical variables when provided by the user.
#' @param rasterFile Quoted full path to raster file. This parameter is required
#'   regardless of whether the template is build from user-provided values or
#'   raster content.
#' @param overwrite A logical to force creating the template from raster content
#'   when raster values are not integers. When generating categorical variables
#'   from raster content, the function will identify the lowest and highest
#'   raster values. By generating the template content from the raster content,
#'   the user is indicating that the raster values are categorical. As such, the
#'   resulting values should be integers. The function will stop if it detects
#'   that the lowest or highest value is not an integer, but this can be
#'   overwritten by setting overwrite = TRUE.
#'
#' @import dplyr
#' @import raster
#' @importFrom tools file_path_sans_ext
#' @importFrom readr write_csv
#'
#' @return A template for providing code definition metadata as a csv file with
#'   the file name of the raster + "_factors.csv" is created in the directory
#'   where the raster resides.
#'
#' @examples
#' \dontrun{
#'
#' write_raster_factors(buildFromFile = TRUE,
#'                      rasterFile = '~/Desktop/smaller_raster.tif')
#'
#' write_raster_factors(rangeStart = 1,
#'                      rangeEnd = 12,
#'                      rasterFile = '~/Desktop/smaller_raster.tif')
#'
#' }
#'
#' @export

write_raster_factors <- function(buildFromFile = FALSE,
                                 rangeStart,
                                 rangeEnd,
                                 rasterFile,
                                 overwrite = FALSE)  {

  # set options -------------------------------------------------------------

  options(scipen = 999)


  # build table from provided range -----------------------------------------

  if (buildFromFile == FALSE) {

    if (missing(rangeStart) | missing(rangeEnd)) {

      stop("please provide start and end range of categorical raster values")

    }

    if (rangeStart >= rangeEnd) {

      stop("beginning range must be less than ending range")

    }

    if (!is.integer(rangeStart) | !is.integer(rangeEnd)) {

      stop("start and end of range must be integers")

    }

    minRasterValue <- rangeStart
    maxRasterValue <- rangeEnd

  } else {

    # build table from raster properties --------------------------------------

    # load raster

    rasterObject <- raster(rasterFile)


    # calculate min and max raster values

    minRasterValue <- cellStats(rasterObject, stat = 'min', na.rm = T)

    if (!is.integer(minRasterValue) & overwrite == FALSE) {

      stop("raster values are not integers - use overwrite to build table")

    }

    maxRasterValue <- cellStats(rasterObject, stat = 'max', na.rm = T)

    if (!is.integer(maxRasterValue) & overwrite == FALSE) {

      stop("raster values are not integers - use overwrite to build table")

    }

  }


  # write raster factor template to file ------------------------------------

  directoryName <- dirname(rasterFile)

  rasterFactorsFileName <- paste0(basename(file_path_sans_ext(rasterFile)), "_factors.csv")

  tibble(
    attributeName = "raster_value",
    code = seq(from = minRasterValue, to = maxRasterValue, by = 1),
    definition = as.character("METADATA_NOT_PROVIDED")
  ) %>%
    write_csv(paste0(directoryName, "/", rasterFactorsFileName))

}
